// This file is automatically generated. Do not edit it directly.
// NOTE: Supabase is deprecated - using Python API backend instead
// This file is kept for compatibility but should not be used

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

// Only initialize if both URL and key are provided
// Otherwise, create a stub client that doesn't crash
let supabaseClient: any = null;

if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
  try {
    supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    });
  } catch (error) {
    console.warn('Supabase initialization skipped - using Python API backend instead');
  }
} else {
  console.warn('Supabase not configured - using Python API backend instead');
  // Create a stub client that won't crash but won't work
  supabaseClient = {
    auth: {
      signInWithPassword: () => Promise.reject(new Error('Supabase not configured - use Python API')),
      signUp: () => Promise.reject(new Error('Supabase not configured - use Python API')),
      signOut: () => Promise.resolve({ error: null }),
      getUser: () => Promise.resolve({ data: { user: null }, error: null }),
      onAuthStateChange: () => ({ data: { subscription: null }, error: null }),
    },
    from: () => ({
      select: () => Promise.resolve({ data: [], error: null }),
      insert: () => Promise.resolve({ data: null, error: { message: 'Supabase not configured' } }),
      update: () => Promise.resolve({ data: null, error: { message: 'Supabase not configured' } }),
      delete: () => Promise.resolve({ data: null, error: { message: 'Supabase not configured' } }),
    }),
  };
}

export const supabase = supabaseClient;